jobs:
 - name: dotnettest
   type: runSh
   runtime:
     nodePool: dynamic__x86_64__WindowsServer_2016__c4_large
   steps:
     - IN: w16test
     - TASK: 
         runtime:
           options:
             imageName: "drydock/w16dotnetcore"
             imageTag: master
         script:        
           - dotnet --version
           - dotnet --info
